module.exports =
  AboutView:       require './about'
  CommitsView:     require './commits'
  ErrorView:       require './error'
  FightsView:      require './fights'
  HomeView:        require './home'
  LeaderboardView: require './leaderboard'
  UserView:        require './user'
  LoginView:       require './login'
  RegisterView:    require './register'
